import Head from "next/head";

import NavigationBar from "../src/components/NavigationBar/NavigationBar";
import Dashboard from "../src/components/Dashboard/Dashboard";

import { checkIfLoggedIn } from "../lib/models/user/helper";
import { User } from "../lib/models/user/User";
import {
  getCommunities,
  getRecentlyAddedCommunities,
  getPopularCommunities,
} from "../lib/models/community/queries";
import { Community } from "../lib/models/community/Community";

type Props = {
  user: User;
  communities: Community[];
  recentlyAddedCommunities: Community[];
  popularCommunities: Community[];
};

export default function Home({
  user,
  communities,
  recentlyAddedCommunities,
  popularCommunities,
}: Props) {
  console.log(popularCommunities);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavigationBar user={user} />
      <Dashboard
        communities={communities}
        recentlyAddedCommunities={recentlyAddedCommunities}
        popularCommunities={popularCommunities}
      />
    </>
  );
}

export async function getServerSideProps(context: any) {
  const user = await checkIfLoggedIn(
    `connect.sid=${context.req.cookies["connect.sid"]}`
  );

  const communities = await getCommunities();

  const recentlyAddedCommunities = await getRecentlyAddedCommunities();

  const popularCommunities = await getPopularCommunities();

  return {
    props: { user, communities, recentlyAddedCommunities, popularCommunities },
  };
}
